image: ruby:2.6

cache:
  paths:
    - vendor/

before_script:
  - gem install bundler
  - bundle install --path vendor

pages:
  stage: build
  script:
    - bundle exec jekyll build
  artifacts:
    paths:
    - _site
  only:
  - master

ssh:
  stage: deploy
  before_script:
    - apt-get update -y
    - apt-get install rsync -y
# Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - rsync -a public/* $SSH_USER@$IP_ADDRESS:/var/www/thinkprivacy.ch/html/ 