image: ruby:2.6

cache:
  paths:
    - vendor/

before_script:
  - gem install bundler
  - bundle install --path vendor

pages:
  stage: build
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

ssh:
  stage: deploy
  before_script:
    - apt-get update -y && apt-get install openssh-client rsync -y
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -a public/* $SSH_USER@199.192.19.197:/var/www/thinkprivacy.ch/html/ 