image: ruby:2.6

before_script:
  - gem install bundler
  - bundle install

pages:
  stage: build
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

ssh:
  stage: deploy
  script:
    - apt install rsync
    - rsync -a public/* $SSH_USER@199.192.19.197:/var/www/thinkprivacy.ch/html/ 