# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 15 # it will paginate after this number
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: ThinkPrivacy
description: ThinkPrivacy is a blog and resource center for all things privacy. Regardless if you’re looking to avoid corporate tracking or government surveillance, we have something to help you.
cover: assets/images/other.jpg
logo: assets/images/2019_logo_white.png
logo_dark: assets/images/2019_logo.png
favicon: assets/images/favicon.ico
production_url: https://thinkprivacy.io/
source_url: https://github.com/thinkprivacyio/thinkprivacy/
CNAME: thinkprivacy.io

# Social info
navigation: True # show the navbar links
subscribers: false # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: thinkprivacyio # replace by your username
facebook: # replace by your username
mastodon: danarel #dont include the @ just your username

# Disqus
disqus: False
disqus_shortname: 

# Google Analytics
google_analytics: 

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: 
  - _plugins

plugins: 
  - jekyll-paginate
  - jekyll-feed
  - github-pages

feed:
  path: feed.xml


# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: thinkprivacyio
repo: thinkprivacy
branch: gh-pages
relative_source: ../thinkprivacy/
destination: ../tp_site/
production_url: https://thinkprivacy.io
source_url:  https://www.github.com/thinkprivacyio/thinkprivacy/ 

exclude:
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
  - _drafts