title: ThinkPrivacy
description: With corporate and government sponsored surveillance programs exploiting your data for profit or motive, isn't it time you started to Think Privacy?
url: "https://www.thinkprivacy.io"
markdown: kramdown
collections:
  authors:
  output: true
exclude: [vendor, LICENSE, build.sh, README.md, Gemfile, Gemfile.lock]
include: [.well-known, keybase.txt, _redirects]